version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - law-mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: lawfarm2021
      MYSQL_DATABASE: lawfarm
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: lawfarm2021
      MYSQL_DB: lawfarm
      AUTH_SECRET_KEY: lawfarm2021
volumes:
  law-mysql-data:

