version: "3.7"

services:
#  db:
#    image: mysql:5.7
#    platform: linux/x86_64
#    volumes:
#      - law-mysql-data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: lawfarm2021
#      MYSQL_DATABASE: lawfarm
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
  api:
#    platform: linux/x86_64
    build: .
    ports:
      - '8000:80'
#    network_mode: "host"
    environment:
      MYSQL_HOST: 10.0.0.223
      MYSQL_USER: root
      MYSQL_PASSWORD: lawfarm2021
      MYSQL_DB: lawfarm
#      ACCESS_TOKEN_SECRET_KEY: lawfarm2021
#    depends_on:
#      - db
  proxy:
    image: nginx:latest
#    platform: linux/x86_64
    ports:
      - '80:80' # common web
      - '443:443' # https
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/web.conf:/etc/nginx/web.conf:ro
      - ./proxy/server-https-common.conf:/etc/nginx/server-https-common.conf:ro
      - /etc/letsencrypt/archive/api.fotone.moe:/etc/ssl
    depends_on:
      - api
volumes:
  law-mysql-data:

