version: "3.7"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - law-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lawfarm2021
      MYSQL_DATABASE: lawfarm
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  api:
    platform: linux/x86_64
    build: .
    ports:
      - "8000:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: lawfarm2021
      MYSQL_DB: lawfarm
#      ACCESS_TOKEN_SECRET_KEY: lawfarm2021
volumes:
  law-mysql-data:

